spring:
#  custom:
#    redis:
#      cluster:  # com.ozz.redis.config.MyRedisClusterConfig
#        nodes: localhost:6379,localhost2:6379
#        password:
#        max-redirects: 3
#        timeout: 3s # 连接超时
#        max-active: 500
#        max-idle: 500
#        max-wait: -1
#        min-idle: 20
  redis: # org.springframework.boot.autoconfigure.data.redis.RedisProperties
    password: x
    timeout: 60s # 连接超时
    sentinel:
      nodes: localhost:17922,localhost:17922
      master: master7922
