spring:
  custom:
    redis:
      cluster:
        nodes: localhost:6379,localhost2:6379
        max-active: 500
        max-idle: 500
        max-redirects: 3
        max-wait: -1
        min-idle: 20
        password:
        timeout: 3000
#  redis:
#    password: x
#    sentinel:
#      master: master7922
#      nodes: localhost:17922,localhost:17922